--- 
abstract: Synchronising to local directories from a repository
author: 
  - Adam Kennedy <cpan@ali.as>
build_requires: 
  Test::More: 0.47
  Test::Script: 0
distribution_type: module
generated_by: Module::Install version 0.68
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: VCS-CSync
no_index: 
  directory: 
    - inc
    - t
requires: 
  Config::Tiny: 2.01
  File::Flat: 1.00
  File::Spec: 0.82
  Getopt::Long: 0
  Params::Util: 0.26
  perl: 5.005
version: 0.02
